PokeJuego/Controllers/PokemonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PokeJuego.Models;

namespace PokeJuego.Controllers
{
    public class PokemonController : Controller
    {
        private dbPokemonEntities db = new dbPokemonEntities();

        // GET: Pokemon
        public ActionResult Index()
        {
            var c_tbPokemon = db.C_tbPokemon.Include(c => c.C_tbAtaqueEspecial).Include(c => c.C_tbAtaques).Include(c => c.C_tbTipoPokemon);
            return View(c_tbPokemon.ToList());
        }



        public ActionResult ListaPokemones()
        {
            var c_tbPokemon = db.C_tbPokemon.Include(c => c.C_tbAtaqueEspecial).Include(c => c.C_tbAtaques).Include(c => c.C_tbTipoPokemon);
            return View(c_tbPokemon.ToList());
        }

        // GET: Pokemon/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            C_tbPokemon c_tbPokemon = db.C_tbPokemon.Find(id);
            if (c_tbPokemon == null)
            {
                return HttpNotFound();
            }
            return View(c_tbPokemon);
        }

        // GET: Pokemon/Create
        public ActionResult Create()
        {
            ViewBag.intAtaqueEsp = new SelectList(db.C_tbAtaqueEspecial, "intAtaqueEsp", "strNombreAtaqueEsp");
            ViewBag.intAtaque = new SelectList(db.C_tbAtaques, "intAtaque", "strNombreAtaque");
            ViewBag.intTipoPokemon = new SelectList(db.C_tbTipoPokemon, "intTipoPokemon", "strTipoPokemon");
            return View();
        }

        // POST: Pokemon/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "intPokemon,strNombrePokemon,strImagen,tnyVida,intTipoPokemon,intAtaque,intAtaqueEsp")] C_tbPokemon c_tbPokemon)
        {
            if (ModelState.IsValid)
            {
                db.C_tbPokemon.Add(c_tbPokemon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.intAtaqueEsp = new SelectList(db.C_tbAtaqueEspecial, "intAtaqueEsp", "strNombreAtaqueEsp", c_tbPokemon.intAtaqueEsp);
            ViewBag.intAtaque = new SelectList(db.C_tbAtaques, "intAtaque", "strNombreAtaque", c_tbPokemon.intAtaque);
            ViewBag.intTipoPokemon = new SelectList(db.C_tbTipoPokemon, "intTipoPokemon", "strTipoPokemon", c_tbPokemon.intTipoPokemon);
            return View(c_tbPokemon);
        }

        // GET: Pokemon/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            C_tbPokemon c_tbPokemon = db.C_tbPokemon.Find(id);
            if (c_tbPokemon == null)
            {
                return HttpNotFound();
            }
            ViewBag.intAtaqueEsp = new SelectList(db.C_tbAtaqueEspecial, "intAtaqueEsp", "strNombreAtaqueEsp", c_tbPokemon.intAtaqueEsp);
            ViewBag.intAtaque = new SelectList(db.C_tbAtaques, "intAtaque", "strNombreAtaque", c_tbPokemon.intAtaque);
            ViewBag.intTipoPokemon = new SelectList(db.C_tbTipoPokemon, "intTipoPokemon", "strTipoPokemon", c_tbPokemon.intTipoPokemon);
            return View(c_tbPokemon);
        }

        // POST: Pokemon/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "intPokemon,strNombrePokemon,strImagen,tnyVida,intTipoPokemon,intAtaque,intAtaqueEsp")] C_tbPokemon c_tbPokemon)
        {
            if (ModelState.IsValid)
            {
                db.Entry(c_tbPokemon).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.intAtaqueEsp = new SelectList(db.C_tbAtaqueEspecial, "intAtaqueEsp", "strNombreAtaqueEsp", c_tbPokemon.intAtaqueEsp);
            ViewBag.intAtaque = new SelectList(db.C_tbAtaques, "intAtaque", "strNombreAtaque", c_tbPokemon.intAtaque);
            ViewBag.intTipoPokemon = new SelectList(db.C_tbTipoPokemon, "intTipoPokemon", "strTipoPokemon", c_tbPokemon.intTipoPokemon);
            return View(c_tbPokemon);
        }

        // GET: Pokemon/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            C_tbPokemon c_tbPokemon = db.C_tbPokemon.Find(id);
            if (c_tbPokemon == null)
            {
                return HttpNotFound();
            }
            return View(c_tbPokemon);
        }

        // POST: Pokemon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            C_tbPokemon c_tbPokemon = db.C_tbPokemon.Find(id);
            db.C_tbPokemon.Remove(c_tbPokemon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PokeJuego/Views/Pokemon/Create.cshtml
@model PokeJuego.Models.C_tbPokemon

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>C_tbPokemon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.strNombrePokemon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strNombrePokemon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strNombrePokemon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strImagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strImagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strImagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tnyVida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tnyVida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tnyVida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.intTipoPokemon, "intTipoPokemon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("intTipoPokemon", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.intTipoPokemon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.intAtaque, "intAtaque", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("intAtaque", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.intAtaque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.intAtaqueEsp, "intAtaqueEsp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("intAtaqueEsp", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.intAtaqueEsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PokeJuego/Views/Pokemon/Delete.cshtml
@model PokeJuego.Models.C_tbPokemon

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>C_tbPokemon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.strNombrePokemon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.strNombrePokemon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.strImagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.strImagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tnyVida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tnyVida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_tbAtaqueEspecial.strNombreAtaqueEsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_tbAtaqueEspecial.strNombreAtaqueEsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_tbAtaques.strNombreAtaque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_tbAtaques.strNombreAtaque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_tbTipoPokemon.strTipoPokemon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_tbTipoPokemon.strTipoPokemon)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PokeJuego/Views/Pokemon/Details.cshtml
@model PokeJuego.Models.C_tbPokemon

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>C_tbPokemon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.strNombrePokemon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.strNombrePokemon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.strImagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.strImagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tnyVida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tnyVida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_tbAtaqueEspecial.strNombreAtaqueEsp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_tbAtaqueEspecial.strNombreAtaqueEsp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_tbAtaques.strNombreAtaque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_tbAtaques.strNombreAtaque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C_tbTipoPokemon.strTipoPokemon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C_tbTipoPokemon.strTipoPokemon)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.intPokemon }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PokeJuego/Views/Pokemon/Edit.cshtml
@model PokeJuego.Models.C_tbPokemon

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>C_tbPokemon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.intPokemon)

        <div class="form-group">
            @Html.LabelFor(model => model.strNombrePokemon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strNombrePokemon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strNombrePokemon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.strImagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.strImagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.strImagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tnyVida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tnyVida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tnyVida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.intTipoPokemon, "intTipoPokemon", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("intTipoPokemon", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.intTipoPokemon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.intAtaque, "intAtaque", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("intAtaque", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.intAtaque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.intAtaqueEsp, "intAtaqueEsp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("intAtaqueEsp", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.intAtaqueEsp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PokeJuego/Views/Pokemon/Index.cshtml
@model IEnumerable<PokeJuego.Models.C_tbPokemon>

@{
    ViewBag.Title = "Index";
}

<link href="~/Content/Custom_CSS/BasicStyles_Div.css" rel="stylesheet" />



<div class="container text-center">
    <label style="font-size:20px">
        Pokedex
    </label>

</div>

@*<div class="container text-center">
    <a href="@Url.Action("Create", "Pokemon")">
        <img src="~/Assets/Images/add.png" width="40" height="40" class="Sombra" style="border-radius:40px" />
    </a>
</div>*@


<div class="container text-center">
    <label style="font-size:20px">
        Selecciona un Pokemon para empezar el enfrentamiento
    </label>

</div>

<br />
<div class="container text-center">


    @foreach (var item in Model)
    {
        var linkImagen = item.strImagen;
        <a href="@Url.Action("SeleccionPersonaje", "Batallas", new { idPokemon = item.intPokemon})">

            <div class="col-sm-2 Bordes-Sombreados-1  " style="margin-left: 90px; margin-right: 90px; margin-bottom: 20px;">
                <img src="@linkImagen" alt="Imagen del Pokemon" width="150" height="150" />
                <br />
                <label style="font-size: 20px; color:black" >
                    @Html.DisplayFor(modelItem => item.strNombrePokemon)
                </label>
            </div>

        </a>

    }

</div>

PokeJuego/Views/Pokemon/ListaPokemones.cshtml
@model IEnumerable<PokeJuego.Models.C_tbPokemon>

<p>
    @Html.ActionLink("Añadir un nuevo pokemon", "Create")
</p>
<table class="table ">
    <tr class="bg-primary">
        <th>
            @Html.DisplayName("Nombre")
        </th>
        <th>
            @Html.DisplayName("Url de la animacion")
        </th>
        <th>
            @Html.DisplayName("PS (Default 200)")
        </th>
        <th>
            @Html.DisplayName("Ataque especial")
        </th>
        <th>
            @Html.DisplayName("Ataque basico")
        </th>
        <th>
            @Html.DisplayName("Tipo")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="bg-info">
        <td>
            @Html.DisplayFor(modelItem => item.strNombrePokemon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.strImagen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tnyVida)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.C_tbAtaqueEspecial.strNombreAtaqueEsp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.C_tbAtaques.strNombreAtaque)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.C_tbTipoPokemon.strTipoPokemon)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.intPokemon }) |
            @Html.ActionLink("Details", "Details", new { id=item.intPokemon }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.intPokemon })
        </td>
    </tr>
}

</table>